name: Deploy to Azure Container App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.angular
          push: true
          tags: ghcr.io/${{ github.repository }}/pokeapp_frontend:${{ github.sha }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.flask
          push: true
          tags: ghcr.io/${{ github.repository }}/pokeapp_backend:${{ github.sha }}

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
          --name poke-tcg-guesser-backend \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image ghcr.io/${{ github.repository }}/pokeapp_backend:${{ github.sha }}

          az containerapp update \
          --name poke-tcg-guesser-frontend \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image ghcr.io/${{ github.repository }}/pokeapp_frontend:${{ github.sha }}